In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install cpp

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Created wheel for cpp: filename=cpp-1.0.0.6-py3-none-any.whl size=7699 sha256=d63e36734f06b9b24208743c474ad0029596448cbddca2b7cb10a0b647776e86
  Stored in directory: c:\users\pc\appdata\local\pip\cache\wheels\0d\17\c1\407294497a858f759e04033d44e4e100e44afa871d8f2a1906
Successfully built cpp
Note: you may need to restart the kernel to use updated packages.


  ERROR: Command errored out with exit status 1:
   command: 'c:\users\pc\appdata\local\programs\python\python36\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-tstw0h6g\\netcdf4_1baeade5e1fa475ab5f046d76783d577\\setup.py'"'"'; __file__='"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-tstw0h6g\\netcdf4_1baeade5e1fa475ab5f046d76783d577\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\pc\AppData\Local\Temp\pip-pip-egg-info-8esdnn_u'
       cwd: C:\Users\pc\AppData\Local\Temp\pip-install-tstw0h6g\netcdf4_1baeade5e1fa475ab5f046d76783d577\
  Complete output (22 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\

In [3]:
#Data manipulation 
#numpy array 

In [8]:
import numpy as np
#from numpy import array as a
#n=np.array(list,dtype=optional and the default np.float32)
n=np.array([2,3,4.01],dtype=np.int8)
n

array([2, 3, 4], dtype=int8)

In [12]:
#casting
a=np.array([2,3,4])
print(a.dtype,a)
a=a.astype(np.float)
print(a.dtype,a)

int32 [2 3 4]
float64 [2. 3. 4.]


In [11]:
a=float(2)
a

2.0

In [19]:
s=np.array([3,np.nan])
print(repr(s))

array([ 3., nan])


In [20]:
s=np.array([3,np.nan],dtype=np.int32)
print(repr(s))

ValueError: cannot convert float NaN to integer

In [22]:
s=np.array([3,np.nan],dtype="<U3")#string
print(repr(s))

array(['3', 'nan'], dtype='<U3')


In [35]:
#infinity
s=np.array([3,np.inf])
print(repr(s))
d=np.array([3,-np.inf])
print(repr(d))
print(np.inf>10000000000000000000000000000000000000000000000.0)
#for string
s=np.array([3,np.inf],dtype="<U3")
print(repr(s))
#for integer
s=np.array([3,np.inf],dtype=np.int32)
print(repr(s))

array([ 3., inf])
array([  3., -inf])
True
array(['3', 'inf'], dtype='<U3')


OverflowError: cannot convert float infinity to integer

In [51]:
#range data--> 1-D array creation
s=np.arange(5)
print(repr(s))
s=np.arange(5.6)
print(repr(s))
#s=np.arange("a")
#print(repr(s)) #error
s=np.arange(-1,5)
print(repr(s))
s=np.arange(1.9999,5,1)
#s=s.astype(dtype=np.int32)
print(repr(s))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3,  4])
array([1.9999, 2.9999, 3.9999, 4.9999])


In [38]:
for i in range(0.1,2.9,1.1):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [65]:
#linspace
s=np.linspace(5,23,num=1000,dtype=np.int32)#default value of num is 50
print(repr(s))

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  9,  9,  9,  9

In [69]:
arr=np.array([[1,2,3,4],[5,6,7]],dtype=object)
arr

array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)